apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/roinov-dtc-129/internal-image
        env: 
        - name: GOOGLE_CLOUD_PROJECT
          value: "roinov-dtc-129"
        ports:
        - containerPort: 8082
            
        
